### ISSUE TITLE
error when building: "build constraints exclude all Go files..."

### ISSUE THREAD

**Issue by chandra-rathina** [uber/h3-go#23]
Having issues with importing uber/h3-go into the project. 
Even tried with playground, it doesn't seem to work.

https://play.golang.org/p/mY_7vHn_IMU

**Comment by Karmadon** [comment]
+1

**Comment by joegilley** [comment]
Hey @chandra-rathina! The go playground does not run with the environment variable `CGO_ENABLED=1` that is needed to compile the h3-go package.  The following cryptic error is returned by Go if this environment variable is not set:

```
go: downloading github.com/uber/h3-go v3.0.1+incompatible
go: extracting github.com/uber/h3-go v3.0.1+incompatible
go: finding github.com/uber/h3-go v3.0.1+incompatible
go build github.com/uber/h3-go: build constraints exclude all Go files in /Users/joegilley/go/pkg/mod/github.com/uber/h3-go@v3.0.1+incompatible
```

which might seem to blame the project's version `+incompatible`, but this is really saying that the package has been found, but doesn't support Go Modules.  I filed #24 to fix this `+incompatible` suffix :) However, this isn't related to the error message from the playground; only the last line is the error message.

This can be demonstrated locally:

```
$ CGO_ENABLED=0 go run hello.go
go: downloading github.com/uber/h3-go v3.0.1+incompatible
go: extracting github.com/uber/h3-go v3.0.1+incompatible
go: finding github.com/uber/h3-go v3.0.1+incompatible
go build github.com/uber/h3-go: build constraints exclude all Go files in /Users/joegilley/go/pkg/mod/github.com/uber/h3-go@v3.0.1+incompatible
$ CGO_ENABLED=1 go run hello.go
0x8928308280fffff
```
```
// hello.go
package main

import (
  "fmt"
  "github.com/uber/h3-go"
)

func main() {
	geo := h3.GeoCoord{
		Latitude:  37.775938728915946,
		Longitude: -122.41795063018799,
	}
	resolution := 9
	fmt.Printf("%#x\n", h3.FromGeo(geo, resolution))
	// Output:
	// 0x8928308280fffff
}
```
If you haven't already, you might try running your project with `CGO_ENABLED=1`.  

When `CGO_ENABLED=0`, the Go compiler will omit all source files that contain `import "CGO"` in them.  In this case, because `h3-go` is only a single Go file that wraps our C core library, that is all of our Go files :) Hence, the build constraints have "excluded" all Go files leaving nothing to compile.

If this isn't your issue, can you include the full error you're seeing, or steps to reproduce?  That will help me investigate more for you.

**Comment by Karmadon** [comment]
Thanks @joegilley

**Comment by nsehgal** [comment]
------

Step 9/14 : RUN CGO_ENABLED=1 go build -o appname
 ---> Running in 2d19340edcc8
# github.com/uber/h3-go
exec: "gcc": executable file not found in $PATH

---------

Tried this getting "exec: "gcc": executable file not found in $PATH". How to fix? Thanks. @joegilley

**Comment by Guanyu1** [comment]
Dear Bro, please do this,will solve your problem.
![image](https://user-images.githubusercontent.com/41404916/132883291-195aac12-848d-40c4-a9df-4969dfba79f8.png)
